### ISSUE TITLE
Usage of eval()

### ISSUE THREAD

**Issue by edorofeyev** [emn178/js-sha1#4]
Version 0.6.0 uses `eval()` at columns `1036` and `1064` (minified version), which is not quite good for browser extension development.

Is it possible to avoid usage of `eval()`?

Previously used version 0.4.1 which did not have any `eval()` statements.

**Comment by emn178** [comment]
This is because https://github.com/emn178/js-md5/issues/8
And I found it won't polyfill unused code in this way.
